import Choices from 'choices.js';

const choicesWall = document.querySelector('.choices');
if(choicesWall){
  const choices= new Choices(choicesWall, {
    searchEnabled: false,
    renderChoiceLimit: -1,
    items: [{
      value: '10',
      label: '10см (+? руб)',
      selected: true,
      disabled: false,
    },
    {
      value: '20',
      label: '20см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '30',
      label: '30см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '40',
      label: '40см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '50',
      label: '50см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '60',
      label: '60см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '70',
      label: '70см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '80',
      label: '80см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '90',
      label: '90см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '100',
      label: '100см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '110',
      label: '110см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '120',
      label: '120см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '130',
      label: '130см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '140',
      label: '140см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '150',
      label: '150см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '160',
      label: '160см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '170',
      label: '170см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '180',
      label: '180см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '190',
      label: '190см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '200',
      label: '200см (+? руб)',
      selected: false,
      disabled: true,
    },],

    choices: [{
      value: '10',
      label: '10см (+? руб)',
      selected: true,
      disabled: false,
    },
    {
      value: '20',
      label: '20см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '30',
      label: '30см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '40',
      label: '40см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '50',
      label: '50см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '60',
      label: '60см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '70',
      label: '70см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '80',
      label: '80см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '90',
      label: '90см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '100',
      label: '100см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '110',
      label: '110см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '120',
      label: '120см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '130',
      label: '130см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '140',
      label: '140см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '150',
      label: '150см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '160',
      label: '160см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '170',
      label: '170см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '180',
      label: '180см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '190',
      label: '190см (+? руб)',
      selected: false,
      disabled: true,
    },
    {
      value: '200',
      label: '200см (+? руб)',
      selected: false,
      disabled: true,
    },],
  });
}
